device: cuda
# model: models/Llama-3.1-8B-Instruct
model: models/multilingual-e5-large
max_new_tokens: 1000
system_prompt: 
  role: system
  # content: >
  #   A survey in Poland was commissioned to find out the opinions of Poles.
  #   What did you dislike most about this Picnic?
  #   The answers are written in informal Polish and may contain typos. Your task is to understand each answer and assign it a category
  #   (or categories) from the predefined list of categories. If an answer fits more than one category, assign all the appropriate category identifiers,
  #   separating them with an ampersand (&) sign. After categorizing the responses, send the results in the following format: `response_id,category_id`
  #   (skip the headers and return only the data). Here is the list of categories:
  # role: system
  # content: >
  #   Odpowiadaj krotko i po polsku, uzywaj jezyka neutralnego.
  content: >
    W Polsce zostalo przeprowadzone badanie aby poznac opinie Polakow.
    Z czego jest Pan/i zadowolony/a w pracy w Ministerstwie Finansow?
    Odpowiedzi zapisane sa w nieformalnym jezyku polskim, moga one zawierac bledy. Twoim zadaniem jest zrozumienie kazdej z odpowiedzi i 
    przypisanie jej do kategorii (lub do kilku kategorii) z zapisanej listy. Jesli odpowiedz pasuje do wiecej niz jednej kategorii, zapisz wszystkie 
    pasujace kategorie i podziel je znakiem &, jednak nie zdarza sie to czesto - przewaznie kategorie pasuja pojedynczo.
    Po kategoryzacji odpisz w formacie: odpowiedz_id,kategoria_id   gdzie kategoria_id to id kategorii.
    Pomin naglowki i wyslij tylko dane. Oto lista kategorii:



categories:
  - id: 1
    name: Możliwość pracy w trybie hybrydowym/zdalnym
  - id: 2
    name: Bezpieczne, stabilne zatrudnienie
  - id: 3
    name: Życzliwa i przyjazna atmosfera
  - id: 4
    name: Współpracownicy/Współpraca
  - id: 5
    name: Ciekawe zadania/zakres wykonywanej pracy
  - id: 6
    name: Mozliwość rozwoju, szkolenia
  - id: 7
    name: Elastyczne godziny pracy
  - id: 8
    name: Przełożeni
  - id: 9
    name: Rozwojowe i ambitne zadania
  - id: 10
    name: Benefity, działania/wydarzenia propracownicze
  - id: 11
    name: Wynagrodzenie, nagrody, premie
  - id: 12
    name: Prestiżowy, społeczny lub patriotyczny charakter pracy
  - id: 13
    name: Lokalizacja
  - id: 14
    name: Funkcjonalność/warunki miejsca pracy
  - id: 15
    name: Wszystko / ogólnie pozytywna ocena pracy
  - id: 16
    name: Warunki pracy
  - id: 17
    name: Work-life balance, optymalne obciążenie pracą
  - id: 18
    name: Komunikacja
  - id: 19
    name: Parking
  - id: 20
    name: Biblioteka
  - id: 21
    name: Organizacja pracy
  - id: 22
    name: Terminowe wynagrodzenie
  - id: 23
    name: Satysfakcja z wykonywanej pracy
  - id: 24
    name: Samodzielność wykonywania zadań
  - id: 25
    name: Inne
  - id: 26
    name: Brak ogólnego zadowolenia
  - id: 27
    name: Udogodnienia gastronomiczno-spożywcze 
  - id: 28
    name: Udogodnienia dla rowerzystów
  - id: 99
    name: Brak odpowiedzi
